Port to Python 3 - fix TypeError
blob had been using str in python2.
str in python2 has been changed to bytes in python3.
Use encode to convert the python2 str to python3 bytes.

fixes error raised while testing collaboration:

Traceback (most recent call last):
  File "/usr/share/sugar/activities/Browse.activity/collabwrapper.py", line 688, in __notify_state_cb
    input_stream = self._get_input_stream()
  File "/usr/share/sugar/activities/Browse.activity/collabwrapper.py", line 736, in _get_input_stream
    return Gio.MemoryInputStream.new_from_data(self._blob, None)
TypeError: Item 0: Must be number, not str

Regression introduced in https://github.com/sugarlabs/collabwrapper/commit/139511702deee7bc443a5a6428e0ab19aaa6cdbe
Also Reported by : Shaan Subbaiah <shaansubbaiah.cs18@bmsce.ac.in> in http://lists.sugarlabs.org/archive/sugar-devel/2020-June/058458.html