Port view source for WebKit2
Reproducer: start Browse 201.2, show Frame, right-click on Browse icon,
click on View Source.

Expected result: source of activity and page source.

Observed result: source of activity only, and an error message in logs;
"AttributeError: 'Browser' object has no attribute 'get_main_frame'"

WebKit2 4.0 API documentation shows get_main_frame is no longer a method
of WebView.  Port the code to WebKit2.

Fixes https://github.com/sugarlabs/browse-activity/issues/57