Remove unnecessary and incorrect self._activity.load_homepage() invocation
Looks like a left-over. Caused the following Traceback:

Traceback (most recent call last):
  File "[...]/Browse.activity/webtoolbar.py", line 413, in _go_home_cb
    self._activity.load_homepage()
AttributeError: 'WebActivity' object has no attribute 'load_homepage'

Signed-off-by: Sascha Silbe <silbe@activitycentral.com>